# Generated by Django 4.1.3 on 2022-11-28 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название задачи')),
                ('is_done', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('done_at', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Когда выполнена')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание задачи')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Задачи',
                'verbose_name_plural': 'Задача',
                'ordering': ('is_done',),
            },
        ),
    ]
