services:
  psql:
    container_name: todo-postgres
    image: "postgres:14.1-alpine"
    env_file:
      - backend/.env
  backend:
    container_name: 'todo-backend'
    image: "python:3.9-alpine"
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    command: bash -c "python manage.py runserver 0.0.0.0:8000"

  frontend:
    container_name: 'todo-frontend'
    image: "node:14.0.0-alpine"
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend

